import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Feed from "~/components/Feed";
import Header from "~/components/Header";
import { SideMenu, useWindowDimensions } from "~/components/SideMenu";

const Home: NextPage = () => {
  const { width } = useWindowDimensions();
  const { user } = useUser();
  return (
    <>
      <Head>
        <title>Bee Social</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen items-center justify-center bg-slate-100 dark:bg-slate-700">
        <SideMenu
          profileImageUrl={user?.profileImageUrl ?? ""}
          width={width ?? 2000}
        />

        <Feed />
      </main>
    </>
  );
};

export default Home;
