import { SignIn, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Feed from "~/components/Feed";
import { SideMenu } from "~/components/SideMenu";

const Home: NextPage = () => {
  const { user } = useUser();
  return (
    <>
      <Head>
        <title>Bee Social</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen items-center justify-center">
        {!user && <SignIn />}

        {user && (
          <>
            <SideMenu profileImageUrl={user?.profileImageUrl ?? null} />
            <Feed />
          </>
        )}
      </main>
    </>
  );
};

export default Home;
